name: cattle_marketplace
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

#----------------PACKAGES-------------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Pack
  cupertino_icons: ^1.0.6
  go_router: ^15.1.2
  provider: ^6.1.2    # Add this line
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2

#---------------- ./PACKAGES END-------------------#

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  #------------- LOCAL ASSETS-------------------#
  assets:
    - assets/icons/
    - assets/images/
    - assets/logos/

  #----------------LOCAL FONTS-------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.ttf
        - asset: assets/fonts/Inter/Inter-Medium.ttf
